[package]
name = "multi-protocol-server"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[[bin]]
name = "multi-protocol-server"
path = "src/main.rs"
doc = false

[dependencies]
orbit-protocols = { path = "../../orbit/protocols" }
tokio = { version = "1.48", features = ["full"] }
